'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {flushSync} from 'react-dom';
import Link from 'next/link';
import {ArrowUpRight, ArrowRight, ChartNoAxesColumnIncreasing, Globe2, Search, Sparkles, FileText, Download, CircleHelp, Check, AlertCircle, LoaderCircle, X, Info} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {reportHtml} from '@/lib/audit/export';
import {sampleAudit} from '@/lib/audit/sample';
import {categories,type Category,type Audit} from '@/lib/audit/types';
const icons={seo:Search,content:FileText,geo:Sparkles};
export default function Home(){
 const [audit,setAudit]=useState(sampleAudit); const [category,setCategory]=useState('all'); const [filter,setFilter]=useState('all');
 const [url,setUrl]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [help,setHelp]=useState(false);const active=useRef<AbortController|null>(null);
 const runAudit=useCallback(async(value:string)=>{
   if(active.current)throw new Error('An audit is already in progress.');
   if(typeof value!=='string'||!value.trim()||value.length>2048)throw new Error('Enter a valid website URL.');
   const controller=new AbortController();active.current=controller;setUrl(value);setLoading(true);setError('');setNotice('');const deadline=setTimeout(()=>controller.abort('timeout'),45000);
   try{const response=await fetch('/api/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:value}),signal:controller.signal});const result=await response.json() as Audit & {error?:string};if(!response.ok)throw new Error(result.error||'The audit could not be completed.');flushSync(()=>{setAudit(result);setCategory('all');setFilter('all');setNotice('Audit complete. Your report is ready.');});return result as Audit;}
   catch(e){const message=controller.signal.aborted?(controller.signal.reason==='timeout'?'This audit took too long. Please try again.':'Audit canceled.'):e instanceof Error?e.message:'The audit could not be completed.';setError(message);throw new Error(message);}
   finally{clearTimeout(deadline);active.current=null;setLoading(false);}
 },[]);
 useEffect(()=>()=>active.current?.abort(),[]);
 useEffect(()=>{
   const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
   try{Promise.resolve(context.registerTool({name:'run_website_audit',title:'Run website audit',description:'Fetch a public webpage and up to 12 internal links, then update the visible audit report. This sends the URL to the audit service and visits the public site.',inputSchema:{type:'object',properties:{url:{type:'string',description:'Public HTTP or HTTPS website URL'}},required:['url'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){if(!input||typeof input!=='object'||typeof (input as {url?:unknown}).url!=='string')throw new Error('A website URL is required.');const a=await runAudit((input as {url:string}).url);return {url:a.url,score:a.score,scores:a.scores,findings:a.findings.length,checkedLinks:a.metrics.checkedLinks};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();
 },[runAudit]);
 function download(){const blob=new Blob([reportHtml(audit)],{type:'text/html;charset=utf-8'});const objectUrl=URL.createObjectURL(blob);const link=document.createElement('a');link.href=objectUrl;link.download=`signal-audit-${new URL(audit.url).hostname}${audit.sample?'-sample':''}.html`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),10000);setNotice('Report downloaded. Open it in a browser to read or save as PDF.');}
 const reportLabel=audit.sample?'Illustrative results':new Date(audit.date).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});

 const findings=audit.findings.filter(f=>(category==='all'||f.category===category)&&(filter==='all'||f.status===filter));
 return <div className="app-shell">
  <header className="site-header"><Link className="brand" href="/" aria-label="Signal home"><span className="brand-icon"><ChartNoAxesColumnIncreasing size={23}/></span>signal<span className="brand-period">.</span></Link><div className="header-section">Website intelligence</div><Button variant="ghost" className="help-button" onClick={()=>setHelp(true)}><CircleHelp/> How it works</Button></header>
  <main>
   <section className="audit-starter"><div className="starter-copy"><div className="eyebrow"><span className="tiny-line"/> FIND YOUR NEXT OPPORTUNITY</div><h1>A clearer picture of your website.</h1><p>Turn your URL into an actionable SEO, content, and AI readiness audit.</p></div><form className="audit-form" onSubmit={e=>{e.preventDefault();void runAudit(url).catch(()=>{});}} aria-busy={loading}><label htmlFor="website-url">Website URL</label><div className="url-control"><Globe2 size={20}/><Input id="website-url" placeholder="https://yourwebsite.com" type="text" inputMode="url" autoComplete="url" value={url} onChange={e=>setUrl(e.target.value)} disabled={loading} aria-describedby="audit-note" maxLength={2048} required/><Button type="submit" disabled={loading}>{loading?<><LoaderCircle className="spin"/> Auditing…</>:<>Run audit <ArrowRight size={17}/></>}</Button></div><p id="audit-note">Public pages only · Up to 12 internal links · Usually under 30 seconds</p>{loading&&<div className="loading-note" role="status"><span>Fetching page content and checking internal links…</span><Button type="button" variant="ghost" onClick={()=>active.current?.abort()}>Cancel</Button></div>}{error&&<p className="form-error" role="alert"><AlertCircle size={16}/>{error}</p>}</form></section>
   <div className="workspace">{notice&&<div className="notice" role="status"><Check size={16}/>{notice}<Button variant="ghost" size="icon-sm" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></Button></div>}
    <div className="report-heading"><div><div className="eyebrow light">YOUR WEBSITE, AT A GLANCE</div><h2>Audit overview <span className={'sample-badge '+(audit.sample?'':'live-badge')}>{audit.sample?'Sample report':'Live audit'}</span></h2><p><Globe2 size={14}/> <span className="audited-url" title={audit.url}>{new URL(audit.url).hostname}{new URL(audit.url).pathname!=='/'?new URL(audit.url).pathname:''}</span> <span className="dot-separator">·</span> {reportLabel}</p></div><Button variant="outline" onClick={download} aria-label="Export report"><Download/> Export report</Button></div>
    <section className="score-grid" aria-label="Audit scores" aria-busy={loading}><div className="overall-card"><div><span className="card-label">Overall health</span><div className="overall-number">{audit.score}<span>/ 100</span></div><span className="health-label">{audit.score>=85?'Strong foundations. Keep improving.':audit.score>=65?'A solid start. Room to grow.':'A few foundations need attention.'}</span></div><div className="score-orbit" aria-hidden="true" style={{background:`conic-gradient(#6c8e50 ${audit.score}%, #cfddc2 0)`}}><ChartNoAxesColumnIncreasing size={38}/></div><div className="overall-foot">Your next improvements start below <ArrowUpRight size={16}/></div></div>
     {(Object.keys(categories) as Category[]).map(key=>{const Icon=icons[key]; return <button key={key} className={'category-card '+(category===key?'selected':'')} onClick={()=>{setCategory(key);setFilter('all');}} aria-pressed={category===key}><div className="category-top"><span className={'category-icon '+key}><Icon size={19}/></span><ArrowUpRight size={17}/></div><h3>{categories[key]}</h3><div className="category-score">{audit.scores[key]}<span>/100</span></div><Progress aria-label={categories[key]+' score'} value={audit.scores[key]} className={'score-progress '+key}/><span className="category-caption">{key==='seo'?'Make your page discoverable':key==='content'?'Make every word work':'Make answers easier to find'}</span></button>})}
    </section>
    <div className="report-columns"><section className="findings-panel"><div className="panel-heading"><h2>Your action plan</h2><span>{audit.findings.length} checks</span></div><Tabs value={category} onValueChange={v=>{setCategory(v);setFilter('all');}}><TabsList variant="line" className="category-tabs"><TabsTrigger value="all">All checks</TabsTrigger><TabsTrigger value="seo">SEO</TabsTrigger><TabsTrigger value="content">Content</TabsTrigger><TabsTrigger value="geo">AI / GEO</TabsTrigger></TabsList></Tabs><div className="filter-row">{(['all','critical','improvement','good'] as const).map(s=><Button key={s} variant="ghost" className={'filter-chip '+(filter===s?'active':'')} onClick={()=>setFilter(s)} aria-pressed={filter===s}>{s==='all'?'All priorities':s==='critical'?'Critical':s==='improvement'?'Improvement':'Good'} <span>{audit.findings.filter(f=>(s==='all'||f.status===s)&&(category==='all'||f.category===category)).length}</span></Button>)}</div><Accordion type="multiple" className="findings-list">{findings.map(f=><AccordionItem value={f.id} key={f.id}><AccordionTrigger className="finding-trigger"><span className={'finding-mark '+f.status} role="img" aria-label={`Priority: ${f.status}`}>{f.status==='good'?<Check size={16}/>:f.status==='critical'?<AlertCircle size={16}/>:<ArrowUpRight size={16}/>}</span><span className="finding-main"><span className="finding-title">{f.title}</span><span className="finding-category">{categories[f.category]}</span></span><span className={'status-badge '+f.status}>{f.status==='critical'?'Critical':f.status==='good'?'Good':'Improvement'}</span></AccordionTrigger><AccordionContent className="finding-details"><p><strong>Evidence</strong><br/>{f.evidence}</p>{f.weight===0&&<span className="unscored-label">Opportunity or unavailable check · Not included in score</span>}<div><strong>What to do</strong><p>{f.recommendation}</p></div></AccordionContent></AccordionItem>)}</Accordion>{findings.length===0&&<p className="no-findings">No checks match this view.</p>}</section>
     <aside className="report-aside"><section className="snapshot-panel"><div className="panel-heading"><h2>Page snapshot</h2><FileText size={18}/></div><dl>{[['Word count',audit.metrics.words.toLocaleString()],['Reading ease',audit.metrics.readingEase===null?'Not scored':`${audit.metrics.readingEase} / 100`],['Heading structure',`${audit.metrics.h1} H1 · ${audit.metrics.h2} H2`],['Images without alt',`${audit.metrics.missingAlt} of ${audit.metrics.images}`],['Internal links checked',`${audit.metrics.checkedLinks} of ${audit.metrics.links}`],['HTML response',`${audit.metrics.responseMs.toLocaleString()} ms`],['HTML size',`${audit.metrics.htmlKb} KB`]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="snapshot-note">Response time covers HTML retrieval, not browser speed or Core Web Vitals.</p><div className="keywords"><h3>Topics found in copy</h3><div>{audit.keywords.map(k=><span key={k.word} title={`${k.count} occurrences · ${k.density}% of extracted words`}>{k.word} <b>{k.count}</b></span>)}{audit.keywords.length===0&&<p>Not enough text to identify topics.</p>}</div><p className="topic-note">Frequency is descriptive, not a keyword target.</p></div><div className="outline-wrap"><Accordion type="single" collapsible><AccordionItem value="outline"><AccordionTrigger>Heading outline</AccordionTrigger><AccordionContent><ol className="heading-outline">{audit.headings.map((h,i)=><li key={i}><b>H{h.level}</b>{h.text||'(empty heading)'}</li>)}{audit.headings.length===0&&<li>No headings found.</li>}</ol></AccordionContent></AccordionItem><AccordionItem value="links"><AccordionTrigger>Internal-link results</AccordionTrigger><AccordionContent><ul className="link-results">{audit.linkResults.map(l=><li key={l.url}><span>{l.url}</span><b className={l.state}>{l.status||'—'} · {l.state==='unknown'?'Inconclusive':l.state==='broken'?'Broken':'Reachable'}</b></li>)}{audit.linkResults.length===0&&<li>{audit.sample?'Run a live audit to inspect links.':'No eligible internal links were found.'}</li>}</ul></AccordionContent></AccordionItem></Accordion></div></section><section className="insight-card"><span className="insight-icon"><Sparkles size={19}/></span><h3>Good for people.<br/>Clear for search.</h3><p>The strongest foundations are the same: useful content, clear structure, and answers worth finding.</p><span>Clarity is your advantage <ArrowUpRight size={16}/></span></section></aside>
    </div><section className="scope-note"><Info size={17}/><div><strong>{audit.sample?'You’re viewing an illustrative sample. Enter a URL above for a live audit.':'A focused audit, with a clear scope.'}</strong><p>We inspect server-delivered HTML and sampled internal links. Scores are heuristic indicators, not search rankings, Core Web Vitals, or AI citation predictions. <button onClick={()=>setHelp(true)}>About the checks</button></p></div></section><footer className="report-footer"><span><span className="footer-brand">signal.</span> Less guesswork. Better websites.</span><span>Heuristic scores · One-page analysis</span></footer>
   </div>
  </main>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="method-dialog"><DialogHeader><DialogTitle>What your audit tells you</DialogTitle><DialogDescription>A focused review of one public page, with evidence you can act on.</DialogDescription></DialogHeader><div className="method-content"><h3>Three perspectives</h3><p><b>SEO foundations</b> checks titles, descriptions, headings, alt attributes, indexing directives, HTTPS, canonical declarations, and up to 12 same-origin links.</p><p><b>Content quality</b> looks at extracted text, English reading ease, paragraph length, and repeated sentences. Word counts and readability are editorial aids, not ranking targets.</p><p><b>AI / GEO readiness</b> looks at text availability, structure, snippet controls, question-led sections, and structured-data opportunities. No special schema, FAQs, or formatting guarantees AI visibility.</p><h3>How scores work</h3><p>Each scored check is weighted: Good = 100, Improvement = 55, Critical = 0. Category scores are weighted averages; overall health averages the three categories. Optional opportunities and unavailable checks are excluded.</p><h3>What is not measured</h3><p>JavaScript-rendered content, visual layout, Core Web Vitals, robots.txt crawl rules, search indexing, backlinks, traffic, whole-site duplicates, and actual AI citations are not measured. HTTP errors other than 404/410 are inconclusive link checks. Schema parsing does not validate eligibility.</p><h3>Your report</h3><p>Export downloads a standalone HTML report containing every finding, including hidden filters. Open it in a browser to read offline or print to PDF. Audits are kept in this page only and reset when you reload.</p><p className="source-links"><a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" target="_blank" rel="noreferrer">Google SEO guidance ↗</a><a href="https://developers.google.com/search/docs/fundamentals/ai-optimization-guide" target="_blank" rel="noreferrer">Google AI guidance ↗</a><a href="https://www.w3.org/WAI/tutorials/images/" target="_blank" rel="noreferrer">W3C alt-text guidance ↗</a></p></div></DialogContent></Dialog>
 </div>
}
