import {parseHTML} from 'linkedom';
import type {Audit,Category,Finding,LinkResult,Status} from './types';
const clean=(s:string|null|undefined)=> (s||'').replace(/\s+/g,' ').trim();
const wordsOf=(s:string)=>s.toLowerCase().match(/[\p{L}]+(?:['’][\p{L}]+)?/gu)||[];
const stop=new Set('the and for that this with from your you are our have has will can more about their they was were into not but all its what how who when where why which these those also use using through each any some than then there here been had would could should does did very just such make get one two new may now out see we us is it of to in on as at by or an a be if so do my me i his her them only no up'.split(' '));
export function discoverLinks(html:string,pageUrl:string):string[]{
 const {document}=parseHTML(html);const urls=new Set<string>();const base=document.querySelector('base[href]')?.getAttribute('href');let resolvedBase=pageUrl;try{if(base)resolvedBase=new URL(base,pageUrl).href}catch{}
 for(const el of document.querySelectorAll('a[href]')){try{const u=new URL(el.getAttribute('href')!,resolvedBase);u.hash='';if(['http:','https:'].includes(u.protocol)&&u.origin===new URL(pageUrl).origin&&u.href!==pageUrl&&!u.username&&!u.password&&!/\.(?:pdf|zip|png|jpe?g|webp|svg|mp4|mp3|css|js)$/i.test(u.pathname))urls.add(u.href);}catch{}}
 return [...urls];
}
export function analyzePage(html:string,url:string,options:{requestedUrl?:string;responseMs?:number;bytes?:number;links?:LinkResult[];robotHeader?:string}={}):Audit{
 const {document}=parseHTML(html);const all=(s:string)=>[...document.querySelectorAll(s)];
 const title=clean(document.querySelector('title')?.textContent);const descriptions=all('meta').filter(e=>e.getAttribute('name')?.toLowerCase()==='description');const description=clean(descriptions[0]?.getAttribute('content'));
 const headings=all('h1,h2,h3,h4,h5,h6').map(e=>({level:Number(e.tagName.slice(1)),text:clean(e.textContent)}));const h1=headings.filter(h=>h.level===1),h2=headings.filter(h=>h.level===2);
 const images=all('img');const missing=images.filter(e=>!e.hasAttribute('alt'));
 const lang=document.documentElement.getAttribute('lang')||'';
 const root=(document.querySelector('main')||document.querySelector('article')||document.body).cloneNode(true) as HTMLElement;
 root.querySelectorAll('script,style,noscript,nav,footer,svg,template,[hidden],[aria-hidden="true"]').forEach(e=>e.remove());
 root.querySelectorAll('p,div,section,li,h1,h2,h3,h4,h5,h6,br,td').forEach(e=>e.appendChild(document.createTextNode(' ')));
 const content=clean(root.textContent),words=wordsOf(content),sentences=content.split(/[.!?]+\s+/).map(clean).filter(s=>wordsOf(s).length>=3);
 const english=/^en(?:-|$)/i.test(lang);let readingEase:number|null=null;
 if(english&&words.length>=100&&sentences.length>=5){const syllables=words.reduce((sum,w)=>sum+Math.max(1,(w.replace(/e$/,'').match(/[aeiouy]+/g)||[]).length),0);readingEase=Math.round(Math.max(0,Math.min(100,206.835-1.015*(words.length/sentences.length)-84.6*(syllables/words.length))));}
 const counts=new Map<string,number>();words.filter(w=>w.length>2&&!stop.has(w)).forEach(w=>counts.set(w,(counts.get(w)||0)+1));
 const keywords=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([word,count])=>({word,count,density:Math.round(count/Math.max(words.length,1)*1000)/10}));
 const sentenceCounts=new Map<string,number>();sentences.filter(s=>wordsOf(s).length>=8).forEach(s=>{const normalized=s.toLowerCase();sentenceCounts.set(normalized,(sentenceCounts.get(normalized)||0)+1)});const repeated=[...sentenceCounts].filter(([,n])=>n>=3);
 const paragraphs=[...root.querySelectorAll('p')].map(e=>clean(e.textContent));const longParagraphs=paragraphs.filter(p=>wordsOf(p).length>120);
 const schemaTypes=new Set<string>();let invalidSchema=0;const schema=all('script').filter(e=>e.getAttribute('type')?.toLowerCase()==='application/ld+json');
 const walk=(v:unknown,depth=0)=>{if(depth>16||!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(x=>walk(x,depth+1));return;}for(const [k,x]of Object.entries(v)){if(k==='@type'){(Array.isArray(x)?x:[x]).filter(y=>typeof y==='string').forEach(y=>schemaTypes.add(y));}else if(typeof x==='object')walk(x,depth+1)}};
 for(const s of schema){try{walk(JSON.parse(s.textContent||''))}catch{invalidSchema++}}
 all('[itemscope][itemtype]').forEach(e=>schemaTypes.add((e.getAttribute('itemtype')||'').split('/').pop()||'Microdata'));
 const metaRobots=all('meta').filter(e=>['robots','googlebot'].includes((e.getAttribute('name')||'').toLowerCase())).map(e=>e.getAttribute('content')||'');
 const robots=[...metaRobots,options.robotHeader||''].join(', ').toLowerCase();
 const directives=metaRobots.flatMap(value=>value.toLowerCase().split(',').map(clean));let botScope='';
 for(const part of (options.robotHeader||'').toLowerCase().split(',')){let token=clean(part);const scoped=token.match(/^([a-z][a-z0-9_-]*):\s*(.*)$/);if(scoped&&!['max-snippet','max-image-preview','max-video-preview','unavailable_after'].includes(scoped[1])){botScope=scoped[1];token=clean(scoped[2]);}if(!botScope||botScope==='googlebot')directives.push(token);}
 const noindex=directives.some(d=>d==='noindex'||d==='none');const nosnippet=directives.some(d=>d==='nosnippet'||/^max-snippet\s*:\s*0$/.test(d));
 const canonicals=all('link').filter(e=>(e.getAttribute('rel')||'').toLowerCase().split(/\s+/).includes('canonical'));let canonical='';try{canonical=canonicals[0]?new URL(canonicals[0].getAttribute('href')||'',url).href:''}catch{canonical='Invalid URL'}
 const findings:Finding[]=[];
 const add=(id:string,category:Category,status:Status,title:string,evidence:string,recommendation:string,weight=1)=>findings.push({id,category,status,title,evidence,recommendation,weight});
 add('title','seo',!title?'critical':all('title').length>1||title.length<20||title.length>65?'improvement':'good',!title?'Give your page a descriptive title':'Review your search title',title?`${title.length} characters: “${title}”. ${all('title').length} title element(s).`:'No non-empty title tag found.','Use one specific title that describes this page. The 20–65 character range is an editorial guide, not a search-engine limit.',2);
 add('description','seo',!description||description.length<70||description.length>170||descriptions.length>1?'improvement':'good','Make your search description useful',description?`${description.length} characters: “${description}”.`:'No non-empty meta description found.','Write a natural, page-specific summary. The 70–170 character range is a review guide; search engines can choose their own snippet.');
 add('h1','seo',h1.length===1&&!!h1[0].text?'good':'improvement',h1.length===1&&!!h1[0].text?'Your page has a clear main heading':'Review your page’s main heading',`${h1.length} H1 heading(s). ${h1.slice(0,3).map(h=>`“${h.text}”`).join(' · ')}`,'Use a clear main heading that reflects the page’s purpose. Multiple H1s are a structure review, not an automatic ranking failure.');
 const skipped=headings.some((h,i)=>i>0&&h.level>headings[i-1].level+1);
 add('outline','seo',skipped?'improvement':'good',skipped?'Keep your heading outline easy to follow':'Heading levels follow a logical order',`${headings.length} headings; ${h2.length} H2 sections. ${skipped?'At least one heading level is skipped.':'No skipped levels detected.'}`,'Nest subheadings under the section they explain. Choose heading levels for structure, not appearance.');
 add('alt','seo',missing.length?'improvement':'good',missing.length?'Give your images a little more context':'Image alt attributes are present',`${missing.length} of ${images.length} images lack an alt attribute.${missing.length?' Examples: '+missing.slice(0,3).map(e=>(e.getAttribute('src')||'(no source)').slice(0,150)).join(', '):''}`,'Add descriptive alt text to informative images. Empty alt text is appropriate for decorative images; this check does not judge the quality of existing descriptions.',2);
 add('indexing','seo',noindex?'critical':'good',noindex?'This page declares that it should not be indexed':'No noindex directive was detected',robots?`Observed directives: ${robots.slice(0,600)}`:'No noindex directive found in supported meta tags or the response header.','Confirm that indexing restrictions are intentional. Absence of noindex does not prove crawlability or actual search indexing.',2);
 add('canonical','seo',!canonical||canonical!==url||canonicals.length>1?'improvement':'good','Check the preferred page URL',`${canonicals.length} canonical declaration(s). ${canonical||'No canonical found.'}`,'Use a canonical when duplicate URLs need consolidation. A canonical pointing elsewhere may be intentional; confirm the preferred destination.',canonical?1:0);
 add('https','seo',url.startsWith('https:')?'good':'critical',url.startsWith('https:')?'A secure connection is in place':'Serve this page over HTTPS',`Final URL: ${url}`,'Use HTTPS consistently for your page and its assets.',2);
 const viewport=all('meta').some(e=>e.getAttribute('name')?.toLowerCase()==='viewport'&&/width\s*=\s*device-width/i.test(e.getAttribute('content')||''));
 add('viewport','seo',viewport?'good':'improvement','Check mobile viewport support',viewport?'A device-width viewport declaration is present.':'No device-width viewport declaration found.','Set a responsive viewport and verify the real layout on mobile. A viewport declaration alone does not prove mobile usability.');
 add('lang','seo',lang?'good':'improvement','Declare the language of your page',lang?`HTML language: ${lang}`:'The HTML element has no language declaration.','Set the correct language for accessibility and reliable language-specific analysis.');
 const links=options.links||[],broken=links.filter(l=>l.state==='broken'),unknown=links.filter(l=>l.state==='unknown'),discovered=discoverLinks(html,url);
 add('links','seo',broken.length?'critical':unknown.length||!links.length?'improvement':'good',broken.length?'Repair broken links in this sample':'Review your internal-link sample',`${links.length} checked of ${discovered.length} eligible internal URLs. ${broken.length} returned 404/410; ${unknown.length} were inconclusive. ${broken.map(l=>l.url).join(' ')}`,'Repair confirmed 404/410 destinations. Restricted, failed, or timed-out requests are inconclusive. The sample cannot establish the health of every link.',links.some(l=>l.state!=='unknown')?2:0);
 add('copy','content',words.length<100?'improvement':'good',words.length<100?'There is limited text to evaluate':'Your page contains readable text',`${words.length.toLocaleString()} words extracted from likely main content.`,'Add information only when it helps the visitor. There is no ideal word count for search; short pages can be appropriate.');
 add('readability','content',readingEase===null||readingEase<50?'improvement':'good',readingEase===null?'Reading ease needs more English prose':readingEase<50?'Make complex passages easier to follow':'Your copy is reasonably easy to follow',readingEase===null?'Not scored: requires a declared English language, at least 100 words and 5 sentences.':`Estimated Flesch reading ease: ${readingEase}/100. This is a language heuristic, not an SEO ranking signal.`,'Review long sentences and unfamiliar terms for your actual audience. Technical content may naturally have a lower reading-ease score.',readingEase===null?0:1);
 add('repetition','content',repeated.length?'improvement':'good',repeated.length?'Review repeated passages':'No heavily repeated sentences found',repeated.length?repeated.slice(0,3).map(([s,n])=>`“${s.slice(0,250)}” appears ${n} times.`).join(' '):'No sentence of at least 8 words appears 3 or more times in extracted text.','Remove unnecessary repeated copy while preserving helpful product names, labels, and required notices.');
 add('paragraphs','content',longParagraphs.length?'improvement':'good',longParagraphs.length?'Give long paragraphs some breathing room':'Paragraph lengths are manageable',`${longParagraphs.length} paragraphs exceed 120 words. This is an editorial threshold.`,'Split dense passages when it improves comprehension. Use specific headings and lists where they help the reader.');
 add('text-access','geo',words.length<50?'improvement':'good','Make essential information available as text',`${words.length} words were available in server-delivered HTML.`,'Keep essential descriptions and answers in accessible text. JavaScript-only or image-only copy may not be visible to this audit.',2);
 add('sections','geo',h2.length?'good':'improvement',h2.length?'Content is organized into distinct sections':'Use descriptive sections to guide readers',`${h2.length} H2 headings found.`,'Organize topics logically and provide direct explanations below headings. No special AI-only formatting is required.');
 const questions=headings.filter(h=>/\?|^(what|how|why|when|where|can|does|is|who)\b/i.test(h.text));
 add('answers','geo',questions.length?'good':'improvement',questions.length?'Question-led sections were found':'Consider the questions visitors need answered',`${questions.length} question-led headings detected. This check is an optional opportunity and does not affect the score.`,'Where useful, answer real visitor questions directly. FAQ sections and FAQ schema are not required for AI visibility.',0);
 add('schema','geo',invalidSchema||!schemaTypes.size?'improvement':'good',invalidSchema?'Repair structured-data JSON syntax':schemaTypes.size?'Structured-data types were detected':'Consider structured data that matches your content',`${schema.length} JSON-LD blocks; ${invalidSchema} could not be parsed. Types: ${[...schemaTypes].join(', ')||'none detected'}.`,'Use relevant types such as Organization, Article, or Product only when supported by visible content. JSON parsing is not schema validation; rich results and AI citations are not guaranteed.',invalidSchema?1:0);
 add('snippets','geo',nosnippet?'improvement':'good',nosnippet?'Snippet controls limit content previews':'No supported snippet restriction was found',nosnippet?`Observed directives: ${robots.slice(0,500)}`:'No nosnippet or max-snippet:0 found in the checked directives.','Confirm any snippet restrictions are intentional. This checks declared controls, not actual AI inclusion.');
 const scores={} as Record<Category,number>;for(const cat of ['seo','content','geo'] as Category[]){const ff=findings.filter(f=>f.category===cat&&f.weight>0);scores[cat]=Math.round(ff.reduce((n,f)=>n+(f.status==='good'?100:f.status==='improvement'?55:0)*f.weight,0)/ff.reduce((n,f)=>n+f.weight,0));}
 const order={critical:0,improvement:1,good:2};findings.sort((a,b)=>order[a.status]-order[b.status]||b.weight-a.weight);
 return {url,requestedUrl:options.requestedUrl||url,title,description,date:new Date().toISOString(),scores,score:Math.round((scores.seo+scores.content+scores.geo)/3),findings,metrics:{words:words.length,readingEase,headings:headings.length,h1:h1.length,h2:h2.length,images:images.length,missingAlt:missing.length,links:discovered.length,checkedLinks:links.length,responseMs:options.responseMs||0,htmlKb:Math.round((options.bytes||new TextEncoder().encode(html).length)/1024),schemaTypes:[...schemaTypes]},keywords,headings:headings.slice(0,100),linkResults:links,limitations:['One page’s server-delivered HTML and up to 12 same-origin links were inspected. JavaScript-rendered content and visual layout were not evaluated.','Core Web Vitals, robots.txt permissions, search indexing, backlinks, traffic, and AI citations were not measured. Response time is not a browser performance score.','Scores use weighted checks: Good = 100, Improvement = 55, Critical = 0. Overall is the average of three categories. Optional opportunities and unavailable checks do not affect scores.','AI / GEO readiness measures general text and structure signals. It does not predict AI citations, validate schema eligibility, or guarantee search rankings.']};
}
